openapi: 3.0.0
info:
  title: URL Shortener API
  version: 1.0.0
  description: API for shortening URLs and managing shortened URLs

servers:
  - url: http://localhost:3003
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Url:
      type: object
      properties:
        originalUrl:
          type: string
          format: uri
        shortCode:
          type: string
        expiresAt:
          type: string
          format: date-time
        clicks:
          type: integer
        createdBy:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateUrlRequest:
      type: object
      required:
        - originalUrl
      properties:
        originalUrl:
          type: string
          format: uri
        expiresIn:
          type: integer
          minimum: 1
          maximum: 365
          description: Number of days until URL expires

    UrlListResponse:
      type: object
      properties:
        urls:
          type: array
          items:
            $ref: '#/components/schemas/Url'
        pagination:
          type: object
          properties:
            total:
              type: integer
            page:
              type: integer
            limit:
              type: integer
            pages:
              type: integer

paths:
  /api/urls:
    post:
      summary: Create a new shortened URL
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUrlRequest'
      responses:
        '201':
          description: URL created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Url'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized

    get:
      summary: Get list of shortened URLs
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: createdBy
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: List of URLs retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UrlListResponse'
        '401':
          description: Unauthorized

  /api/urls/info/{shortCode}:
    get:
      summary: Get information about a shortened URL
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: shortCode
          required: true
          schema:
            type: string
      responses:
        '200':
          description: URL information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Url'
        '401':
          description: Unauthorized
        '404':
          description: URL not found

  /api/urls/{shortCode}:
    delete:
      summary: Delete a shortened URL
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: shortCode
          required: true
          schema:
            type: string
      responses:
        '204':
          description: URL deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: URL not found

  /{shortCode}:
    get:
      summary: Redirect to original URL
      parameters:
        - in: path
          name: shortCode
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect to original URL
        '404':
          description: URL not found 